### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by Ferrarisrex** [Winterfoxxy-0/GoGuardian-Bypass#5]
I get error:
        
       Mixed Content: The page at 'https://ggby.bss.design/' was loaded over HTTPS, but requested an insecure frame 'http://https//www.bing.com'. This request has been blocked; the content must be served over HTTPS.
it happens to all websites I visit.

**Comment by Winterfoxxy-0** [comment]
https://github.com/luphoria/UBer
use this instead, it works better
